### ISSUE TITLE
Color prefixes?

### ISSUE THREAD

**Issue by sgbrooks056** [felixletsplayYT/ChatPex#1]
For example, I tried using '&4[Admin]' and '&4[Admin&4' to color the prefix, but it just shows the &4 in the actual prefix in-game. Is there any fix for this?

Thank you for making this plugin, it was the only one that gives my groups prefixes from PEX on version 1.10

**Comment by strifel** [comment]
Do you get the colorful Prefix only in chat/tab or do you get in nothing
